
# This file is part of the ReactPHP Foundation <https://github.com/itnelo/reactphp-foundation>.
#
# (c) 2020 Pavel Petrov <itnelo@gmail.com>.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @license https://opensource.org/licenses/mit MIT

ARG PHP_VERSION

FROM php:${PHP_VERSION}-cli

ARG TIMEZONE
ARG DEPLOYMENT_PATH

WORKDIR ${DEPLOYMENT_PATH}

# see .dockerignore
COPY --chown=www-data:www-data . .

USER root

# system
RUN apt-get update && apt-get install -qy --no-install-recommends \
        # composer
        unzip

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# timezone
RUN ln -snf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && echo ${TIMEZONE} > /etc/timezone && \
    printf '[PHP]\ndate.timezone = "%s"\n', ${TIMEZONE} > /usr/local/etc/php/conf.d/tzone.ini && \
    date

# xdebug
RUN pecl install xdebug-beta && docker-php-ext-enable xdebug
COPY docker/dev/app/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# pcntl
RUN docker-php-ext-install pcntl

COPY docker/dev/app/php.ini /usr/local/etc/php/conf.d/php.ini

# composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# permissions
RUN chown www-data:www-data /var/www ${DEPLOYMENT_PATH}

USER www-data

# dependencies
RUN composer install --no-dev --no-interaction --no-scripts --classmap-authoritative --ansi

# configurations
RUN cp config/parameters.yml.dev.dist config/parameters.yml

CMD ["bin/app"]
