
services:
    app.event_loop:
        alias: 'react.event_loop.stream_select'
        public: true

    # react
    react.event_loop.stream_select:
        class: React\EventLoop\StreamSelectLoop
        factory: ['@react.event_loop_factory', create]

    react.event_loop_factory:
        class: React\EventLoop\Factory
