
services:
    # react
    react.stream.writable_resource_stream.stdout:
        class: React\Stream\WritableResourceStream
        arguments:
            - !php/const STDOUT
            - '@react.event_loop.stream_select'
