
services:
    app.request.handler:
        alias: 'app.request.handler.example_handler'

    app.request.handler.example_handler:
        class: Foundation\Request\Handler\ExampleHandler
        arguments:
            - '@app.log.logger.stdout'
            - '@app.request.uri.matcher'
