
services:
    app.request.uri.matcher:
        alias: 'app.request.uri.matcher.array_matcher'

    app.request.uri.matcher.array_matcher:
        class: Foundation\Request\Uri\Matcher\ArrayMatcher
        arguments:
            -   /: 'main-page'
